[package]
name = "hlbsp"
version = "0.1.0"
authors = ["r4v3n6101 <raven6107@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "*"
map_impl = { path = "map_impl" }
bsp = { path = "bsp" }
wad = { path = "wad" }
itertools = "*"

[dependencies.image]
version = "*"
default-features = false
features = ["png"]
